### ISSUE TITLE
URL Rewriting.

### ISSUE THREAD

**Issue by VottonDev** [LoliHook/Old-Pomfe.me#1]
Would grab a video from a directory and writes the video name to url (domain.com/videoname) and removes the file extension too.

**Comment by ghost** [comment]
It's very easy to do, depends on if you've written the grabbing part already and mainly want to remove the file extension.

The Video's name should be picked up automatically, so you should only work on the file extension part.

Best Regards, 
Rith

**Comment by VottonDev** [comment]
Removing the file extension isn't hard but i will work on the rewriting the URL Part.
